### ISSUE TITLE
App crash during parsing url

### ISSUE THREAD

**Issue by plb7777** [59de44955ebd/FDM-UL#2]
In the add download dialog parse using yt-dlp is there and if i use url other than youtube it crashed all the time. And while using youtube link it only shows 360p why not all. And please donot limit its parsing to youtube only enable all supported sites.

**Comment by 59de44955ebd** [comment]
Please provide an example YouTube URL, for which the dialog does not show higher resolutions (like 720p), although they are actually available. But note that this dialog deliberately never shows available HLS or DASH streaming URLs, because FDM obviously can't handle them, it's a pure HTTP/HTTPS downloader. To download from such streaming URLs, you instead need tools like ffmpeg (or JDownloader as ffmpeg GUI). But anyways, usually for HD videos on YouTube there should at least also be a 720p HTTP download URL available.

Please also provide an example URL for which using the yt-dlp feature crashes the app all the time.

**Comment by 59de44955ebd** [comment]
Below the yt-dlp output for some arbitrary YouTube video (https://www.youtube.com/watch?v=ea9reHDIrOo). Note that only the 2 formats marked yellow are actual HTTP **download** URLs, and therefor the only ones that FDM can, well, actually download. And the dialog correctly shows both of them, 360p and 720p.

![example](https://github.com/59de44955ebd/FDM-UL/assets/12278038/44d970ab-994a-4084-9e25-f39f2bb77d82)

**Comment by 59de44955ebd** [comment]
I found and fixed the crash problem, please download and try new version 1.1:
https://github.com/59de44955ebd/FDM-UL/releases/tag/v1.1

The problem was that yt-dlp adds warning messages even when argument "-q" for quiet is specified, and those warning messages then corrupted the JSON output that FDM-UL tries to read. In the new version those warning messages are now turned off by additional argument "--no-warnings". I also deactivated exceptions in the JSON parser, so now such problems with corrupted JSON input should never crash the app, but instead fail silently.
