### ISSUE TITLE
Revamp of FDM to a new level

### ISSUE THREAD

**Issue by plb7777** [59de44955ebd/FDM-UL#3]
Hi
I have some pre requisite questions
1. Can you rewrite as whole using the base codes provided by FDM
2. Can you make browser extension (chrome, firefox)
3. Can you modify the logic of add download 

If yes, please consider the followings,
1. remove all the tab in the main download table provide only one.
2. Add menu as File, Downloads, Tools, Help
3. In File add sub menus like add download, parse url etc
4. In tools add site manager, scheduler etc
5. during parsing the url add a progressbar so that the app should not crash.

Thanks

**Comment by plb7777** [comment]
OR
Can you work on browser extension and developed browser extension for the old FDM that support download files and videos from web pages.

**Comment by 59de44955ebd** [comment]
Short answer: no.
The point of this "Ultra Light" version of FDM was to get rid of irrelvant features and make the app as simple as possible. It was never about customizing the classic interface or creating a new downloader application.

Concerning browser addons: there are good browser addons for Chrome and Firefox that allow to extract download URLs, e.g. "Video DownloadHelper, and once you have the URL, you can either paste it into FDM manually or create a simple bookmarklet that sends them to FDM's Web interface via JS fetch. Here the URL of a minimal example bookmarklet that would send any page's current URL to FDM: 

`javascript:(function(){fetch('http://localhost:8888/adddownload.req?URL='+encodeURI(location.href))})();`

Of course for this to work FDM has to run and its Web interface has to be activated (on default port 8888). And here a more sophisticated bookmarklet that tries to detect video elements in the current browser tab and sends their source URLs to FDM:

`javascript:(function(){const%20vids=document.getElementsByTagName('video');if%20(vids.length){const%20v=vids[0];if%20(v.src.startsWith('blob:')){if%20(window.jwplayer){const%20fn=window.jwplayer().getPlaylist()[0].file;fetch('http://localhost:8888/adddownload.req?URL='+encodeURI(fn));}else%20window.alert('This%20streaming%20hoster%20is%20not%20supported%20since%20it%20uses%20encrypted%20HLS%20URLs,%20please%20select%20a%20different%20hoster.');}else%20{console.log(v.src);fetch('http://localhost:8888/adddownload.req?URL='+encodeURI(v.src));}return;}const%20frms=document.getElementsByTagName('iframe');for(let%20frm%20of%20frms){console.log('iframe',%20frm.src);if%20(!frm.src)frm=frm.documentElement.getElementsByTagName('iframe')[0];if%20(frm.src%20!=''%20&&%20!frm.src.includes('facebook')&&%20!frm.src.includes('google')){location.href=frm.src;break;}}})();`

**Comment by plb7777** [comment]
can you please show me step by step guide to enable this js to detect download from browser and move to fdm.

**Comment by 59de44955ebd** [comment]
Well, first you should know what bookmarklets are:
https://en.wikipedia.org/wiki/Bookmarklet

They are in fact a very powerful browser feature and can replace all kind of "addons/plugins", provided that you know to code in JavaScript. Basically they are just ordinary bookmarks, but instead of pointing to a static URL they store a javascript://... URL.

To get going, go to this page 
https://59de44955ebd.github.io/bookmarklet-editor/
and drag the "FDM-Fetch" box on the top left corner to your browser's bookmark/favorites bar, done. You now have my second example bookmarklet stored in your browser as bookmark "FDM-Fetch" (but of course you can rename it to whatever you like).

If you now navigate to some HTTPS-based video hoster like e.g. streamtape or dood and start a video (so the actual video URL is known to the browser), you can click on this "FDM-Fetch" bookmark to pass the URL to FDM, which will immediately start to download it, and you can close the browser tab. But again, for this to work obviously FDM has to run and its web interface must be activated.

**Comment by plb7777** [comment]
Hi,
Can it be possible you to write packed browser extension for firefox and chrome only. Because bookmarlet is not always capturing the download, to minimize time just modify already present fdm extension for chrome and firefox.
As far as i remember with "nsProcessW_modified.dll" and "ytparser.dll" files FDM can handle dash downloads but while parsing it freezes sometimes.
So i request you to kindly check and make time to develop
1. Create/Modify browser extension
2.  Modify/Create FDM to support http, https, dash, hls downloads.

Thanks

**Comment by 59de44955ebd** [comment]
Hi,
I guess I already answered this in issue "https://github.com/59de44955ebd/FDM-UL/issues/2": FDM is a pure HTTP/HTTPS downloader. HLS and DASH streams can't just be "downloaded", an application that allows to save them as video files must understand a lot about media and streaming technology, and that is exactly what the great tool ffmpeg is meant for. So either use ffmpeg for this directly, or some of the available wrappers for it: yt-dlp, JDownloader, Video DownloadHelper's companion app, ...
I will never try to integrate ffmpeg into FDM itself, that's just not what the tool is meant for.

I also won't try to create a browser addon, first, because this would cost money - I would need a commercial certificate for signing it, since today both chrome and firefox require addons to be signed - and who should pay me for doing this? And second, this would contrast the idea of FDM-UL, to be as simple as possible, It's just a good and stable HTTP/HTTPS downloader that allows accelerated/ multi-segment downloads, and that's it. If you need a browser addon for downloading video streams, install "Video DownloadHelper" instead.
